version: 0.2

phases:
    build:
        on-failure: ABORT
        commands:
        - pwd
        - ls -la
        - ./gradlew jar
artifacts:
    files:
    - build/libs/screenshot-comopare-test.jar
    #discard-paths: no | yes
    #base-directory: location
    #exclude-paths: excluded paths
    #enable-symlinks: no | yes
    s3-prefix: modules