version: 0.2

phases:
    build:
        on-failure: ABORT
        commands:
        - pwd
        - ls -la
        - ./gradlew jar
        #- echo aaaa > artifact.txt
artifacts:
    files:
    - build/libs/screenshot-comopare-test.jar
    - artifact.txt
    #s3-prefix: test-reports/
    s3-prefix: modules/