version: '3.9'

services:
  dev:
    build:
      context: ./docker
      args:
        - USER=$USER
        - GROUP=$USER
    ports:
      - "8088:8088"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      #- DISPLAY=unix$DISPLAY バグでDISPLAY環境変数が正しく参照できない https://github.com/microsoft/vscode-remote-release/issues/7565
      - DISPLAY=unix:0
