FROM {{{ imagebuilder:parentImage }}}
{{{ imagebuilder:environments }}}

# yumアップデートとその他パッケージのインストール
RUN yum update -y && \
    yum install -y zip tar bzip2 unzip

# タイムゾーンの設定
RUN yum install -y tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \

# 日本語環境のセットアップ
RUN yum install -y glibc-langpack-ja ipa-gothic-fonts

# ブラウザをインストール
RUN aws s3 cp s3://${S3BucketName}/modules/installBrowser.sh /tmp/installBrowser.sh && \
    chmod +x /tmp/installBrowser.sh && \
    /tmp/installBrowser.sh chrome && \
    /tmp/installBrowser.sh firefox && \
    /tmp/installBrowser.sh edge