AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    GithubAccessToken:
        Type: String
        NoEcho: true

Mappings:
    Env:
        "443244910989":
            Name: evl
            Role: se

Resources:
    # CloudWatchLogsを暗号化するキー
    LogEncryptKey:
        Type: AWS::KMS::Key
        Properties:
            EnableKeyRotation: true
            KeySpec: SYMMETRIC_DEFAULT
            KeyPolicy:
                Version: 2012-10-17
                Statement:
                # ロックアウトを防ぐためルートユーザーに全ての操作を許可
                -   Effect: Allow
                    Action: "kms:*"
                    Resource: "*"
                    Principal:
                        AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
                # ログを暗号化できるようCloudWatchLogsに権限を付与
                -   Effect: Allow
                    Action:
                    - kms:Encrypt
                    - kms:Decrypt
                    - "kms:ReEncrypt*"
                    - "kms:GenerateDataKey*"
                    - kms:DescribeKey
                    Resource: "*"
                    Principal:
                        Service: !Sub logs.${AWS::Region}.amazonaws.com

    # キーのエイリアス
    LogEncryptKeyAlias:
        Type: AWS::KMS::Alias
        Properties:
            AliasName: !Sub
            - alias/user-bsdxxxx-${Env}-log-encrypt-key
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            TargetKeyId: !Ref LogEncryptKey

    # テストを実行するCodeBuildProjectのサービスロール
    CodeBuildServiceRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub
            - user-bsdxxxx-${Env}-codebuild-role
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            Policies:
            -   PolicyName: !Sub
                - user-bsdxxxx-${Env}-codebuild-policy
                - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action: s3:PutObject
                        Resource: !Sub
                        - "${S3BucketArn}/modules/*"
                        - { S3BucketArn: !ImportValue S3BucketArn }
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    Effect: Allow
                    Principal:
                        Service: codebuild.amazonaws.com
                    Action: sts:AssumeRole
            #PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/bgl-Boundaries-SE

    # CodeBuildの実行ログを出力するロググループ
    CodeBuildLogGroupAndPolicy:
        Type: BBBBBBB::Logs::LogGroupAndPolicy::MODULE
        Properties:
            Name: codebuild
            RoleName: !Ref CodeBuildServiceRole
            LogEncryptKeyArn: !GetAtt LogEncryptKey.Arn

    # Githubからクローンするための認証情報
    CodeBuildSourceCredential:
        Type: AWS::CodeBuild::SourceCredential
        Properties:
            AuthType: PERSONAL_ACCESS_TOKEN
            ServerType: GITHUB
            Token: !Ref GithubAccessToken

    # テストを実行するCodeBuildプロジェクト
    CodeBuildProject:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: !Sub
            - user-bsdxxxx-${Env}-build-jar
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            ServiceRole: !Ref CodeBuildServiceRole
            # Githubからソースを取得する
            Source:
                Type: GITHUB
                Auth:
                    Resource: !Ref CodeBuildSourceCredential
                    Type: OAUTH
                GitCloneDepth: 1
                Location: https://github.com/yx-saku/gradle-selenium.git
            #SourceVersion: main
            SourceVersion: master
            # ImageBuilderでビルドしたコンテナイメージを使用する
            Environment:
                Image: !Sub
                - ${ECRRepositoryUri}:${ImageTag}
                - {
                    ECRRepositoryUri: !ImportValue ECRRepositoryUri,
                    ImageTag: !ImportValue ImageTag
                }
                Type: LINUX_CONTAINER
                ImagePullCredentialsType: CODEBUILD
                ComputeType: BUILD_GENERAL1_SMALL
                EnvironmentVariables:
                -   Name: S3_BUCKET
                    Type: PLAINTEXT
                    Value: !ImportValue S3BucketName
            # S3にテストレポート出力
            Artifacts:
                Type: S3
                Name: modules
                Location: !ImportValue S3BucketName
                NamespaceType: NONE
                EncryptionDisabled: true
            # CloudWatchLogsとS3にログ出力
            LogsConfig:
                CloudWatchLogs:
                    GroupName: !Ref CodeBuildLogGroupAndPolicy.LogGroup
                    Status: ENABLED
                S3Logs:
                    EncryptionDisabled: false
                    Location: !Sub
                    - ${S3BucketArn}/logs/codebuild
                    - { S3BucketArn: !ImportValue S3BucketArn }
                    Status: ENABLED

Outputs:
    CodeBuildProjectName:
        Value: !Ref CodeBuildProject
        Export:
            Name: CodeBuildProjectName
    CodeBuildProjectArn:
        Value: !GetAtt CodeBuildProject.Arn
        Export:
            Name: CodeBuildProjectArn
    LogEncryptKeyArn:
        Value: !GetAtt LogEncryptKey.Arn
        Export:
            Name: LogEncryptKeyArn