AWSTemplateFormatVersion: "2010-09-09"

Mappings:
    Env:
        "443244910989":
            Name: evl

Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub
            - user-bsdxxxx-${Env}-screenshot-compare-test
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            AccessControl: Private
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                -   ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            LifecycleConfiguration:
                Rules:
                -   Id: MoveToGlacierAndExpire
                    Status: Enabled
                    Transitions:
                    -   TransitionInDays: 30
                        StorageClass: GLACIER
                    ExpirationInDays: 365
                    Prefix: "test_reports/"
                -   Id: MoveToGlacierAndExpireLogs
                    Status: Enabled
                    Transitions:
                    -   TransitionInDays: 30
                        StorageClass: GLACIER
                    ExpirationInDays: 365
                    Prefix: "logs/"
            VersioningConfiguration:
                Status: Enabled

    BucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref S3Bucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                -   Sid: IPAllow
                    Effect: Allow
                    Principal: '*'
                    Action:
                    - s3:GetObject
                    Resource: !Sub "${S3Bucket.Arn}/test_reports/*"
                    Condition:
                        IpAddress:
                            aws:SourceIp:
                            - 192.168.11.1
                            - 192.168.11.2

Outputs:
    BucketName:
        Value: !Ref S3Bucket
        Description: Name of the S3 bucket
        Export:
            Name: BucketName

    BucketArn:
        Value: !GetAtt S3Bucket.Arn
        Description: ARN of the S3 bucket
        Export:
            Name: BucketArn
