# 直すところ
# ・いろんな権限はリソースポリシー側にまとめた方がいいのでは？（CodeBuildからS3への権限とか）
# ・権限最小化の見直し
# →ロールはそんなにキツキツじゃなくていいのでは
# ・Component1個でよくない？　もしくはDockerFileにしちゃうか
# ・JUnitレポートの出力はいらない
# ・S3とCloudWatchLogs両方にログ出力しているものはCloudWatchLogsに寄せた方が良いのでは？（保存期間も1年にする）
# ・アクセスログのバケットにログをまとめた方がよくないか？→変更コスト高そう
# ・「ログ」と言う単位でロググループとスタックまとめる？→微妙かも、考える

# これは諦める
# ・繰り返しプロパティの共通化　ForEachとか　よっぽとはまるケース以外は諦める
# ・コンポーネントバージョンの自動更新
# ・テンプレートを1個にまとめる→変更コスト高そう

AWSTemplateFormatVersion: "2010-09-09"

Mappings:
    Env:
        "443244910989":
            Name: evl

Resources:
    # テストレポートその他を保存するメインのS3バケット
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub
            - user-bsdxxxx-${Env}-test-automation
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            # SSE-S3で暗号化
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                -   BucketKeyEnabled: true
                    ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            # バージョニング有効化
            VersioningConfiguration:
                Status: Enabled
            LifecycleConfiguration:
                Rules:
                - # 3ヶ月後にGlacierに移動、1年後に削除
                    Id: delete-test-reports
                    Prefix: test-reports/
                    Status: Enabled
                    Transitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    NoncurrentVersionTransitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    ExpirationInDays: 366
                - # 3ヶ月後にGlacierに移動、1年後に削除
                    Id: delete-old-condebuild-logs
                    Prefix: logs/CodeBuild/
                    Status: Enabled
                    Transitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    NoncurrentVersionTransitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    ExpirationInDays: 366
                - # 3ヶ月後にGlacierに移動、1年後に削除
                    Id: delete-old-imagebuilder-logs
                    Prefix: logs/ImageBuilder/
                    Status: Enabled
                    Transitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    NoncurrentVersionTransitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    ExpirationInDays: 366
                - # Lambda関数から取得したテストケースは1日で削除
                    Id: delete-temp-testcases
                    Prefix: temp-testcases/
                    Status: Enabled
                    ExpirationInDays: 1
            LoggingConfiguration:
                DestinationBucketName: !Ref AccessLogS3Bucket
                LogFilePrefix: s3AccessLog/

    # メインバケットのバケットポリシー
    S3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref S3Bucket
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                # 社内からテストレポートへのアクセス許可
                -   Effect: Allow
                    Action: s3:GetObject
                    Resource: !Sub "${S3Bucket.Arn}/test-reports/*/allure-report/*"
                    Principal: "*"
                    Condition:
                        IpAddress:
                            aws:SourceIp:
                            - 192.168.11.1/32

    # メインバケットへのアクセスログを保管するバケット
    AccessLogS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub
            - user-bsdxxxx-${Env}-access-log
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            # SSE-S3で暗号化
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                -   BucketKeyEnabled: true
                    ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            # バージョニング有効化
            VersioningConfiguration:
                Status: Enabled
            # ログ配置を許可
            #AccessControl: LogDeliveryWrite
            LifecycleConfiguration:
                Rules:
                - # 3ヶ月後にGlacierに移動、1年後に削除
                    Id: delete-access-log
                    Prefix: s3AccessLog/
                    Status: Enabled
                    Transitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    NoncurrentVersionTransitions:
                    -   StorageClass: GLACIER
                        TransitionInDays: 90
                    ExpirationInDays: 366

    # アクセスログの保存を許可するバケットポリシー
    AccessLogS3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref AccessLogS3Bucket
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                -   Effect: Allow
                    Principal:
                        Service: logging.s3.amazonaws.com
                    Action: s3:PutObject
                    Resource: !Sub "${AccessLogS3Bucket.Arn}/s3AccessLog/*"
                    Condition:
                        ArnLike:
                            aws:SourceArn: !GetAtt S3Bucket.Arn
                        StringEquals:
                            aws:SourceAccount: !Ref AWS::AccountId

Outputs:
    S3BucketName:
        Value: !Ref S3Bucket
        Export:
            Name: S3BucketName
    S3BucketArn:
        Value: !GetAtt S3Bucket.Arn
        Export:
            Name: S3BucketArn