AWSTemplateFormatVersion: "2010-09-09"

Mappings:
    Env:
        "443244910989":
            Name: evl
            Role: se

Resources:

    GetTestCaseFromLambdaLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            KmsKeyId: !ImportValue LogEncryptKeyArn
            LogGroupName: !Sub
            - user-bsdxxxx-${Env}-get-testcase-from-lambda-log-group
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            RetentionInDays: 90

    GetTestCaseFromLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub
            - user-bsdxxxx-${Env}-get-testcase-from-lambda-role
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            Policies:
            -   PolicyName: !Sub
                - user-bsdxxxx-${Env}-get-testcase-from-lambda-policy
                - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
                PolicyDocument:
                  !Rain::Include ../cf-packages/GetTestCaseFromLambdaPolicy.yml
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement: { Effect: Allow, Action: sts:AssumeRole, Principal: { Service: lambda.amazonaws.com } }
            #PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/bgl-Boundaries-SE

    GetTestCaseFromLambda:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Sub
            - user-bsdxxxx-${Env}-get-testcase-from-lambda
            - { Env: !FindInMap [ Env, !Ref AWS::AccountId, Name ] }
            Runtime: nodejs16.x
            Handler: index.handler
            Role: !GetAtt GetTestCaseFromLambdaRole.Arn
            Timeout: 900
