AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Env:
        Type: "String"
        Default: "aaa"

Resources:
    ScreenshotCompareTestBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Sub "script-test-stack-s3-${Env}"
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false

    ScreenshotCompareTestBucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref ScreenshotCompareTestBucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -   Sid: 'PublicReadForGetBucketObjects'
                        Effect: 'Allow'
                        Principal: '*'
                        Action:
                            - 's3:GetObject'
                        Resource: !Sub 'arn:aws:s3:::${ScreenshotCompareTestBucket}/*'

    ScreenshotCompareTestBucket2:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Sub "script-test-stack-s3-${Env}2"
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false